obj-$(CONFIG_KEXEC_LOAD) += kexec_load.o

kexec_load-objs := \
	kexec.o machine_kexec.o mmu.o sys.o core.o relocate_kernel.o \
	proc-v7.o tlb-v7.o cache-v7.o abort-ev7.o copypage-v6.o entry-common.o driver_sys.o
